insert into BIBLIOTHEQUE(ID,TYPE,RUE,NUMERO,CODE_POSTAL,VILLE,NOM,PRENOM) values(1,'SCOLAIRE','Boulevard des Batignoles',11,77330,'PARIS','DURAND','Pierre');
insert into BIBLIOTHEQUE(ID,TYPE,RUE,NUMERO,CODE_POSTAL,VILLE,NOM,PRENOM) values(2,'UNIVERSITAIRE','rue petit',221,77330,'LYON','MARTIN','Jean');
insert into BIBLIOTHEQUE(ID,TYPE,RUE,NUMERO,CODE_POSTAL,VILLE,NOM,PRENOM) values(3,'ASSOCIATIVE','rue grand',33,77330,'MARSEILLE','DUPOND','Lolo');
insert into BIBLIOTHEQUE(ID,TYPE,RUE,NUMERO,CODE_POSTAL,VILLE,NOM,PRENOM) values(4,'SCOLAIRE','avenue Leclerc',44,77330,'NANTES','FERRE','Titi');

insert into LIVRE(ID,ISBN,TITRE,AUTEUR,PAGE_NUMBER,GENRE) values(1,'ISBN-0001','Les robots','Asimov',100,'FICTION');
insert into LIVRE(ID,ISBN,TITRE,AUTEUR,PAGE_NUMBER,GENRE) values(2,'ISBN-0002','la Tulipe','jean Dujardin',120,'SCIENTIFIQUE');
insert into LIVRE(ID,ISBN,TITRE,AUTEUR,PAGE_NUMBER,GENRE) values(3,'ISBN-0003','Etre ou ne pas etre','Shakespeare',130,'PHILOSOPHIE');
insert into LIVRE(ID,ISBN,TITRE,AUTEUR,PAGE_NUMBER,GENRE) values(4,'ISBN-0004','maths','Jean Petit',90,'ETUDES');

insert into BIBLIOTHEQUE_LIVRE_JPAS(BIBLIOTHEQUE_ID,LIVRE_JPAS_ID) values(1,1);
insert into BIBLIOTHEQUE_LIVRE_JPAS(BIBLIOTHEQUE_ID,LIVRE_JPAS_ID) values(1,3);
insert into BIBLIOTHEQUE_LIVRE_JPAS(BIBLIOTHEQUE_ID,LIVRE_JPAS_ID) values(2,2);
insert into BIBLIOTHEQUE_LIVRE_JPAS(BIBLIOTHEQUE_ID,LIVRE_JPAS_ID) values(3,3);
insert into BIBLIOTHEQUE_LIVRE_JPAS(BIBLIOTHEQUE_ID,LIVRE_JPAS_ID) values(3,4);
insert into BIBLIOTHEQUE_LIVRE_JPAS(BIBLIOTHEQUE_ID,LIVRE_JPAS_ID) values(4,1);
insert into BIBLIOTHEQUE_LIVRE_JPAS(BIBLIOTHEQUE_ID,LIVRE_JPAS_ID) values(4,3);
insert into BIBLIOTHEQUE_LIVRE_JPAS(BIBLIOTHEQUE_ID,LIVRE_JPAS_ID) values(4,4);
